[build]
  command = "npm install" # Instala tus dependencias de Node.js
  publish = "." # La carpeta a desplegar (tu HTML, CSS, JS, etc.)
  functions = "netlify/functions" # Donde Netlify buscar치 tus funciones

[functions]
  node_bundler = "esbuild" # Para una compilaci칩n m치s r치pida de funciones